Variables:
  Org: jamie
  Project: crypto
Resources:
  S3Destination: s3-jamie-general-data-lake
  LogGroup: /aws/jamie/crypto
  EcsCluster: ecs-jamie-general-fargate
  EcrRepo: ecr-jamie-crypto-firehose-producer
  SecretsManagerSecret: TiingoApiToken
